import json

notebook = {
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# Day 43: LangGraph State Machines (Nodes & Edges)\n",
        "\n",
        "Welcome to Day 43 of the AI Engineering Mastery program! We are now deep into **Phase 4: Agent Orchestration & Multi-Agent Systems**. Today, we focus on moving beyond linear, sequential chains (like simple LCEL chains) into complex, cyclical, and dynamic workflows using **LangGraph**.\n",
        "\n",
        "## Core Theory: The \"Why\" and \"How\" of LangGraph\n",
        "\n",
        "### The \"Why\"\n",
        "Traditional LangChain `Chain` objects or basic LCEL (LangChain Expression Language) graphs represent Directed Acyclic Graphs (DAGs). This means data flows from start to finish without loops. However, true *Agentic workflows* are almost never linear. Agents need to:\n",
        "1. Make a decision.\n",
        "2. Take an action (e.g., search the web).\n",
        "3. Observe the outcome.\n",
        "4. Loop back to step 1 to evaluate if more actions are needed or if they should return a final answer.\n",
        "\n",
        "**LangGraph** is built precisely for this. It extends LangChain to support stateful, cyclical workflows—the foundation of true autonomous agents.\n",
        "\n",
        "### The \"How\": State, Nodes, and Edges\n",
        "LangGraph models agent workflows as **State Machines** using three primary concepts:\n",
        "\n",
        "1.  **State (`State`):** A shared data structure (usually a `typing.TypedDict` or Pydantic model) that is passed around. Every node reads from it and writes updates to it. This is your agent's \"memory\" for the current run.\n",
        "2.  **Nodes (Functions):** Python functions that perform work. A node receives the current `State`, does something (calls an LLM, queries a DB, runs a tool), and returns a dictionary with *updates* to the state.\n",
        "3.  **Edges (Logic):** The routing rules. \n",
        "    *   *Normal Edges:* Always go from Node A to Node B.\n",
        "    *   *Conditional Edges:* Run a function to inspect the state and decide dynamically which node to go to next. This is how we implement \"if/else\" routing and loops.\n",
        "\n",
        "By structuring our application this way, we gain immense control, observability, and the ability to pause/resume execution (human-in-the-loop).\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## Code Implementation: Building a StateGraph\n",
        "\n",
        "Let's build a robust, production-grade LangGraph workflow. We will create a simple support ticket triage system. It decides if a ticket should be routed to a \"human\" or an \"AI_agent\".\n",
        "\n",
        "Notice the strict type hinting, docstrings, and isolation of side effects."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "import os\n",
        "import random\n",
        "from typing import TypedDict, Literal\n",
        "from langchain_core.messages import HumanMessage, AIMessage, BaseMessage\n",
        "from langgraph.graph import StateGraph, END\n",
        "\n",
        "# 1. Define the State\n",
        "# This is the \"schema\" of our shared memory.\n",
        "class AgentState(TypedDict):\n",
        "    \"\"\"\n",
        "    Represents the state of our agentic workflow.\n",
        "    \n",
        "    Attributes:\n",
        "        ticket_query (str): The initial user request.\n",
        "        messages (list[BaseMessage]): History of interactions or scratchpad notes.\n",
        "        route_decision (Literal[\"AI_agent\", \"human\", \"\"]): The outcome of the triage.\n",
        "    \"\"\"\n",
        "    ticket_query: str\n",
        "    messages: list[BaseMessage]\n",
        "    route_decision: Literal[\"AI_agent\", \"human\", \"\"]\n",
        "\n",
        "\n",
        "# 2. Define Nodes (The Workers)\n",
        "\n",
        "def triage_node(state: AgentState) -> dict:\n",
        "    \"\"\"\n",
        "    Analyzes the ticket_query and decides the routing.\n",
        "    In production, this would use an LLM with structured output.\n",
        "    Here, we simulate it for predictable local execution.\n",
        "    \"\"\"\n",
        "    query = state[\"ticket_query\"].lower()\n",
        "    \n",
        "    # Simulated logic: if it mentions \"billing\" or \"refund\", send to human.\n",
        "    if \"billing\" in query or \"refund\" in query:\n",
        "        decision: Literal[\"human\", \"AI_agent\"] = \"human\"\n",
        "    else:\n",
        "        decision = \"AI_agent\"\n",
        "        \n",
        "    # We return a dictionary mapping state keys to their NEW values.\n",
        "    # LangGraph will automatically merge these updates into the current state.\n",
        "    return {\n",
        "        \"route_decision\": decision,\n",
        "        \"messages\": [AIMessage(content=f\"Triage complete: routing to {decision}.\")]\n",
        "    }\n",
        "\n",
        "def ai_agent_node(state: AgentState) -> dict:\n",
        "    \"\"\"\n",
        "    Handles general inquiries autonomously.\n",
        "    \"\"\"\n",
        "    # In reality, you'd call an LLM here.\n",
        "    response_msg = AIMessage(content=\"AI Agent: I can help you reset your password or configure your dashboard. What do you need?\")\n",
        "    \n",
        "    return {\n",
        "        # Notice we don't update route_decision, only messages.\n",
        "        # By default, state updates overwrite. If messages were defined with `operator.add` in TypedDict (Annotated), they would append.\n",
        "        # For simplicity here without Annotated, we manually append.\n",
        "        \"messages\": state.get(\"messages\", []) + [response_msg]\n",
        "    }\n",
        "\n",
        "def human_escalation_node(state: AgentState) -> dict:\n",
        "    \"\"\"\n",
        "    Routes complex/sensitive issues to a human queue.\n",
        "    \"\"\"\n",
        "    response_msg = AIMessage(content=\"System: Ticket escalated to human support queue due to billing/refund keywords.\")\n",
        "    return {\n",
        "        \"messages\": state.get(\"messages\", []) + [response_msg]\n",
        "    }\n",
        "\n",
        "\n",
        "# 3. Define Conditional Edges (The Logic)\n",
        "\n",
        "def route_after_triage(state: AgentState) -> Literal[\"human_node\", \"ai_node\"]:\n",
        "    \"\"\"\n",
        "    Inspects the state after triage and dictates the next node.\n",
        "    \n",
        "    Returns the string name of the next node to execute.\n",
        "    \"\"\"\n",
        "    if state[\"route_decision\"] == \"human\":\n",
        "        return \"human_node\"\n",
        "    else:\n",
        "        return \"ai_node\"\n",
        "\n",
        "\n",
        "# 4. Build and Compile the Graph\n",
        "\n",
        "def build_graph():\n",
        "    # Initialize graph with the State definition\n",
        "    workflow = StateGraph(AgentState)\n",
        "\n",
        "    # Add all nodes. (name_of_node, function_to_execute)\n",
        "    workflow.add_node(\"triage\", triage_node)\n",
        "    workflow.add_node(\"ai_node\", ai_agent_node)\n",
        "    workflow.add_node(\"human_node\", human_escalation_node)\n",
        "\n",
        "    # Define standard start edge (where execution begins)\n",
        "    workflow.set_entry_point(\"triage\")\n",
        "\n",
        "    # Define conditional edge from triage to either ai_node or human_node\n",
        "    workflow.add_conditional_edges(\n",
        "        \"triage\",            # Source node\n",
        "        route_after_triage,  # Routing function\n",
        "        {                    # Mapping of function outputs to target node names\n",
        "            \"human_node\": \"human_node\",\n",
        "            \"ai_node\": \"ai_node\"\n",
        "        }\n",
        "    )\n",
        "\n",
        "    # Define terminal edges (where execution ends)\n",
        "    workflow.add_edge(\"ai_node\", END)\n",
        "    workflow.add_edge(\"human_node\", END)\n",
        "\n",
        "    # Compile into a Runnable\n",
        "    return workflow.compile()\n",
        "\n",
        "app = build_graph()\n",
        "print(\"LangGraph StateMachine compiled successfully!\")\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### Executing the Graph\n",
        "\n",
        "Let's test both pathways of our compiled LangGraph."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# Test 1: AI Routing (No billing keywords)\n",
        "print(\"--- TEST 1: Technical Issue ---\")\n",
        "initial_state_1: AgentState = {\n",
        "    \"ticket_query\": \"How do I reset my API key?\",\n",
        "    \"messages\": [],\n",
        "    \"route_decision\": \"\"\n",
        "}\n",
        "\n",
        "try:\n",
        "    # .invoke() runs the graph synchronously\n",
        "    result_1 = app.invoke(initial_state_1)\n",
        "    print(\"Final State Decision:\", result_1[\"route_decision\"])\n",
        "    for msg in result_1[\"messages\"]:\n",
        "        print(\"- \", msg.content)\n",
        "except Exception as e:\n",
        "    print(f\"Execution Error: {e}\")\n",
        "\n",
        "\n",
        "# Test 2: Human Routing (Billing keyword)\n",
        "print(\"\\n--- TEST 2: Billing Issue ---\")\n",
        "initial_state_2: AgentState = {\n",
        "    \"ticket_query\": \"I need a refund for last month's billing cycle.\",\n",
        "    \"messages\": [],\n",
        "    \"route_decision\": \"\"\n",
        "}\n",
        "\n",
        "try:\n",
        "    result_2 = app.invoke(initial_state_2)\n",
        "    print(\"Final State Decision:\", result_2[\"route_decision\"])\n",
        "    for msg in result_2[\"messages\"]:\n",
        "        print(\"- \", msg.content)\n",
        "except Exception as e:\n",
        "    print(f\"Execution Error: {e}\")\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## Practical Lab / Homework\n",
        "\n",
        "**Your Task:** Enhance the StateGraph provided below to include a \"Review\" step, creating a true cycle/loop.\n",
        "\n",
        "1.  **Context:** We are building a \"Drafting Agent\" that writes an email and then a \"Review Agent\" that checks it. \n",
        "2.  **State:** We have defined `EmailState` for you.\n",
        "3.  **Implement `draft_node`:** Generate a mock email body and set `needs_revision=True` initially to force a cycle.\n",
        "4.  **Implement `review_node`:** Check the `email_body`. If it lacks the word 'APPROVED', append ' (APPROVED)' and set `needs_revision=False`. Otherwise, leave it as is.\n",
        "5.  **Edges:** Create a conditional edge from `review_node`. If `needs_revision` is True, route back to `draft_node`. If False, route to `END`.\n",
        "\n",
        "Fill in the logic below, then compile and run."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "class EmailState(TypedDict):\n",
        "    topic: str\n",
        "    email_body: str\n",
        "    needs_revision: bool\n",
        "    iterations: int\n",
        "\n",
        "def draft_node(state: EmailState) -> dict:\n",
        "    \"\"\"Generates or revises the email draft.\"\"\"\n",
        "    # For safety against infinite loops, we track iterations\n",
        "    current_iters = state.get(\"iterations\", 0)\n",
        "    topic = state[\"topic\"]\n",
        "    \n",
        "    if current_iters == 0:\n",
        "        body = f\"Draft 1: Here is information regarding {topic}.\"\n",
        "    else:\n",
        "        # Simulate fixing the draft based on feedback\n",
        "        body = state.get(\"email_body\", \"\") + \" -> Now with revisions!\"\n",
        "        \n",
        "    return {\n",
        "        \"email_body\": body,\n",
        "        \"iterations\": current_iters + 1\n",
        "    }\n",
        "\n",
        "def review_node(state: EmailState) -> dict:\n",
        "    \"\"\"Reviews the draft and decides if it passes.\"\"\"\n",
        "    iters = state.get(\"iterations\", 0)\n",
        "    \n",
        "    # Simulate: If we've drafted twice, approve it.\n",
        "    if iters >= 2:\n",
        "        return {\n",
        "            \"needs_revision\": False,\n",
        "            \"email_body\": state[\"email_body\"] + \" [APPROVED]\"\n",
        "        }\n",
        "    else:\n",
        "        return {\n",
        "            \"needs_revision\": True\n",
        "        }\n",
        "\n",
        "def review_routing(state: EmailState) -> Literal[\"draft\", \"__end__\"]:\n",
        "    \"\"\"Conditional routing logic based on review outcome.\"\"\"\n",
        "    if state.get(\"needs_revision\", True):\n",
        "        return \"draft\"\n",
        "    return \"__end__\"\n",
        "\n",
        "def build_cyclic_graph():\n",
        "    builder = StateGraph(EmailState)\n",
        "    builder.add_node(\"draft\", draft_node)\n",
        "    builder.add_node(\"review\", review_node)\n",
        "    \n",
        "    builder.set_entry_point(\"draft\")\n",
        "    builder.add_edge(\"draft\", \"review\")\n",
        "    \n",
        "    # Loop logic using conditional edge\n",
        "    builder.add_conditional_edges(\n",
        "        \"review\",\n",
        "        review_routing,\n",
        "        {\n",
        "            \"draft\": \"draft\",\n",
        "            \"__end__\": END\n",
        "        }\n",
        "    )\n",
        "    return builder.compile()\n",
        "\n",
        "# Run the lab\n",
        "try:\n",
        "    cyclic_app = build_cyclic_graph()\n",
        "    lab_result = cyclic_app.invoke({\n",
        "        \"topic\": \"Project Update\",\n",
        "        \"email_body\": \"\",\n",
        "        \"needs_revision\": True,\n",
        "        \"iterations\": 0\n",
        "    })\n",
        "    print(\"\\n--- Lab Result ---\")\n",
        "    print(f\"Final Body: {lab_result['email_body']}\")\n",
        "    print(f\"Total Iterations: {lab_result['iterations']}\")\n",
        "except Exception as e:\n",
        "    print(f\"Lab Execution Error: {e}\")\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## Common Pitfalls in Production\n",
        "\n",
        "1.  **Infinite Loops (The Agent that never sleeps):**\n",
        "    *   *The Problem:* A cyclical graph where the `conditional_edge` never routes to `END`. The agent gets stuck iterating endlessly (costing you money via LLM token usage).\n",
        "    *   *The Solution:* Always implement a fallback or a hard counter (like `iterations` in the lab above) or use LangGraph's built-in `recursion_limit` parameter when invoking the graph (`app.invoke(state, config={\"recursion_limit\": 10})`).\n",
        "2.  **State Mutation Bugs (Appending vs Overwriting):**\n",
        "    *   *The Problem:* Standard `TypedDict` overwrites existing values. If you want to *append* to a list (like a message history), and you simply return `{\"messages\": [new_msg]}`, you will wipe out previous history.\n",
        "    *   *The Solution:* Use `typing.Annotated` with a reducer function (like `operator.add`) when defining the `State`, e.g., `messages: Annotated[list, add]`. This instructs LangGraph to append automatically.\n",
        "3.  **Missing Default Keys in State:**\n",
        "    *   *The Problem:* Accessing `state[\"missing_key\"]` in a node throws a `KeyError` if that key hasn't been set by an earlier node or initial state.\n",
        "    *   *The Solution:* Always initialize the full state schema upfront or use `state.get(\"key\", default_value)` defensively in your nodes."
      ]
    }
  ],
  "metadata": {},
  "nbformat": 4,
  "nbformat_minor": 5
}

with open("modules/day_43.ipynb", "w") as f:
    json.dump(notebook, f, indent=2)

print("Created modules/day_43.ipynb successfully!")
