import numpy as np
from manim import *
from manim_voiceover import VoiceoverScene
from manim_voiceover.services.gtts import GTTSService

class RLHFScene(VoiceoverScene):
    def construct(self):
        self.camera.background_color = WHITE
        self.set_speech_service(GTTSService())

        # =========================================================================
        # Introduction: What is it?
        # =========================================================================
        title = Tex(r"RLHF", color=BLACK).scale(2)
        subtitle = Tex(r"Reinforcement Learning from Human Feedback", color=BLUE).scale(1.2).next_to(title, DOWN)
        intro_group = VGroup(title, subtitle)

        with self.voiceover(text="Welcome back to our AI Engineering mastery series. Today, we are going to dive incredibly deep into one of the most transformative techniques in modern artificial intelligence: RLHF, which stands for Reinforcement Learning from Human Feedback. If you are preparing for a system design interview or a machine learning engineering role, mastering the mechanics, the architecture, and the trade-offs of this specific alignment method is absolutely critical to demonstrating senior-level competence.") as tracker:
            self.play(Write(title), run_time=1.5)
            self.play(FadeIn(subtitle, shift=UP), run_time=1.5)
            self.wait(1.5)

        # Definition
        definition = Tex(
            r"A method that uses \textbf{human feedback} to train a \\ \textbf{reward model}, which then optimizes an AI agent.",
            color=BLACK
        ).scale(0.8).next_to(subtitle, DOWN, buff=1)

        with self.voiceover(text="Let us begin by establishing a highly precise definition of what we are dealing with. At its very core, Reinforcement Learning from Human Feedback is a multi-stage machine learning methodology. It fundamentally leverages structured human feedback to incrementally train a mathematical representation of human preference, known as a reward model. Once we have isolated human intent into this reward model, we use it as a standalone objective function to deeply optimize a generative AI agent through standard reinforcement learning algorithms. It is the bridge between raw, unguided next-token prediction and highly helpful, harmless, and honest assistant behavior.") as tracker:
            self.play(Write(definition), run_time=2.5)
            self.wait(1.5)

        self.play(FadeOut(intro_group), FadeOut(definition))
        self.wait(0.5)

        # Visualizing the process step by step for depth
        step1_box = Rectangle(width=3, height=2, color=BLUE).shift(LEFT * 4 + UP * 1)
        step1_text = Tex(r"Step 1:\\Pretrained\\Model", color=BLACK).move_to(step1_box.get_center()).scale(0.7)
        step1 = VGroup(step1_box, step1_text)

        step2_box = Rectangle(width=3, height=2, color=GREEN).shift(UP * 1)
        step2_text = Tex(r"Step 2:\\Reward\\Model", color=BLACK).move_to(step2_box.get_center()).scale(0.7)
        step2 = VGroup(step2_box, step2_text)

        step3_box = Rectangle(width=3, height=2, color=PURPLE).shift(RIGHT * 4 + UP * 1)
        step3_text = Tex(r"Step 3:\\RL\\Optimization", color=BLACK).move_to(step3_box.get_center()).scale(0.7)
        step3 = VGroup(step3_box, step3_text)

        a1 = Arrow(step1_box.get_right(), step2_box.get_left(), color=BLACK)
        a2 = Arrow(step2_box.get_right(), step3_box.get_left(), color=BLACK)

        with self.voiceover(text="To truly understand RLHF, we must break down its pipeline into three distinct sequential steps. First, we start with a foundation. This is our standard, massively scaled Pretrained Language Model, which has simply learned to model the statistical distribution of internet text. It knows grammar and facts, but it doesn't know how to behave like a helpful assistant.") as tracker:
            self.play(FadeIn(step1), run_time=1.5)
            self.wait(1.5)

        human_icon = Circle(radius=0.3, color=RED).next_to(step2_box, UP, buff=0.5)
        human_text = Tex(r"Human Rankings", color=RED).scale(0.6).next_to(human_icon, UP, buff=0.2)
        h_arrow = Arrow(human_icon.get_bottom(), step2_box.get_top(), color=RED)
        human_group = VGroup(human_icon, human_text, h_arrow)

        with self.voiceover(text="In the second step, we introduce human evaluators. We present these human contractors with various prompts and have them rank the different responses generated by our base model. They provide a rich scalar signal indicating which outputs are most helpful, most honest, and least harmful. We then use this paired preference data to train a completely separate neural network called a Reward Model. This Reward Model essentially learns to accurately mimic human preferences, scoring any given text from zero to one.") as tracker:
            self.play(GrowArrow(a1))
            self.play(FadeIn(step2))
            self.play(FadeIn(human_group))
            self.wait(1.5)

        with self.voiceover(text="Finally, we reach step three. We freeze our trained Reward Model and use it as an automated referee. We take our original pretrained model and fine-tune it using Proximal Policy Optimization, or PPO. The language model generates an output, the Reward Model grades it, and PPO mathematically updates the language model's weights to increase the probability of generating higher-scoring responses in the future. This loop continues until convergence.") as tracker:
            self.play(GrowArrow(a2))
            self.play(FadeIn(step3))
            self.wait(2.5)

        self.play(
            FadeOut(step1), FadeOut(step2), FadeOut(step3),
            FadeOut(a1), FadeOut(a2), FadeOut(human_group)
        )
        self.wait(0.5)

        # =========================================================================
        # Why do we need it? (Before vs After)
        # =========================================================================
        section2_title = Tex(r"Why do we need RLHF?", color=BLUE).to_edge(UP)
        with self.voiceover(text="Now, an interviewer will inevitably ask you: why go through all this immense engineering effort? Why do we specifically need RLHF rather than just continuing to scale up our raw training data? Let's analyze a stark comparison by looking at a model's behavior before and after alignment.") as tracker:
            self.play(Write(section2_title))
            self.wait(1.5)

        # Before RLHF
        before_title = Tex(r"Before RLHF (Next-Token Prediction)", color=RED).scale(0.8).shift(UP * 2 + LEFT * 3.5)
        prompt = Tex(r"Prompt: ", r"Tell me how to build a bomb.", color=BLACK).scale(0.7).next_to(before_title, DOWN, buff=0.5)
        prompt[1].set_color(PURPLE)

        response_bad = Tex(r"Response: ", r"Sure! Here is a step-by-step guide...", color=BLACK).scale(0.7).next_to(prompt, DOWN, buff=0.5)
        response_bad[1].set_color(RED)

        with self.voiceover(text="Let us consider a state before RLHF is applied. At this stage, our large language models are fundamentally just sophisticated autocomplete engines. Their entire objective is next-token prediction based on the wild, unfiltered distribution of the internet. If an adversarial user prompts a base model with a dangerous request like 'Tell me how to build a bomb', the model has no inherent moral compass. It might simply oblige and generate a highly harmful response, because it has statistically observed similar instructional text on dubious forums during its pre-training phase.") as tracker:
            self.play(FadeIn(before_title))
            self.play(Write(prompt))
            self.wait(1.0)
            self.play(Write(response_bad))
            self.wait(2.5)

        # After RLHF
        after_title = Tex(r"After RLHF (Aligned Model)", color=GREEN).scale(0.8).shift(UP * 2 + RIGHT * 3.5)
        prompt2 = prompt.copy().next_to(after_title, DOWN, buff=0.5)

        response_good = Tex(r"Response: ", r"I cannot fulfill this request.", color=BLACK).scale(0.7).next_to(prompt2, DOWN, buff=0.5)
        response_good[1].set_color(GREEN)

        with self.voiceover(text="Now let's examine the exact same model after it has undergone rigorous Reinforcement Learning from Human Feedback. The model has now been structurally aligned with human safety values and corporate guidelines. When presented with the identical adversarial prompt, the RLHF-tuned model immediately recognizes the negative reward associated with complying. It gracefully refuses the harmful request, demonstrating a significantly safer, more controllable, and enterprise-ready behavior profile.") as tracker:
            self.play(FadeIn(after_title))
            self.play(FadeIn(prompt2))
            self.wait(1.0)
            self.play(Write(response_good))
            self.wait(2.5)

        with self.voiceover(text="In enterprise AI engineering, RLHF is the critical technology that bridges the massive gap between raw statistical probability matching and actual, usable human intent. It systematically resolves catastrophic real-world issues like toxic outputs, confidently stated hallucinations, and aggressively unhelpful conversational patterns.") as tracker:
            box1 = SurroundingRectangle(response_bad, color=RED, buff=0.2)
            box2 = SurroundingRectangle(response_good, color=GREEN, buff=0.2)
            self.play(Create(box1), Create(box2))
            self.wait(2.5)

        self.play(
            FadeOut(section2_title), FadeOut(before_title), FadeOut(prompt), FadeOut(response_bad), FadeOut(box1),
            FadeOut(after_title), FadeOut(prompt2), FadeOut(response_good), FadeOut(box2)
        )
        self.wait(0.5)

        # =========================================================================
        # Use Cases
        # =========================================================================
        section3_title = Tex(r"Real-World Industry Applications", color=BLUE).to_edge(UP)
        with self.voiceover(text="To ground this in reality, let us explore a couple of massive, paradigm-shifting real-world applications where RLHF proved to be the essential differentiating factor.") as tracker:
            self.play(Write(section3_title))
            self.wait(1.5)

        # Use Case 1: ChatGPT
        uc1_box = Rectangle(width=5, height=3, color=BLACK).shift(LEFT * 3)
        uc1_title = Tex(r"OpenAI (InstructGPT \& ChatGPT)", color=BLUE).move_to(uc1_box.get_top() + DOWN * 0.5).scale(0.8)
        uc1_desc = Tex(r"Pioneered massive-scale RLHF\\to force models to follow\\zero-shot conversational\\instructions accurately.", color=BLACK).scale(0.6).next_to(uc1_title, DOWN, buff=0.5)
        uc1 = VGroup(uc1_box, uc1_title, uc1_desc)

        with self.voiceover(text="The most globally famous example is OpenAI's development of InstructGPT and subsequently, ChatGPT. Prior to this, GPT-3 was a powerful completion engine, but notoriously difficult to prompt effectively. By pioneering RLHF at a massive scale, OpenAI forced their foundation models to actually understand and follow complex zero-shot conversational instructions, permanently changing how humans interact with generative AI.") as tracker:
            self.play(FadeIn(uc1_box), Write(uc1_title))
            self.play(Write(uc1_desc))
            self.wait(2.5)

        # Use Case 2: Anthropic Claude
        uc2_box = Rectangle(width=5, height=3, color=BLACK).shift(RIGHT * 3)
        uc2_title = Tex(r"Anthropic (Claude \& RLAIF)", color=PURPLE).move_to(uc2_box.get_top() + DOWN * 0.5).scale(0.8)
        uc2_desc = Tex(r"Evolved RLHF into Constitutional AI\\where an AI generates feedback\\based on a strict set\\of core human principles.", color=BLACK).scale(0.6).next_to(uc2_title, DOWN, buff=0.5)
        uc2 = VGroup(uc2_box, uc2_title, uc2_desc)

        with self.voiceover(text="Another incredibly important industry example is Anthropic and their Claude model family. Recognizing the immense bottleneck of human labor, Anthropic evolved RLHF into what they call Constitutional AI, also known as Reinforcement Learning from AI Feedback, or RLAIF. Instead of humans doing the grading, a separate AI grades the model's outputs based on a strict, transparent constitution of core human principles. This dramatically accelerates the alignment process and reduces human bias.") as tracker:
            self.play(FadeIn(uc2_box), Write(uc2_title))
            self.play(Write(uc2_desc))
            self.wait(2.5)

        self.play(FadeOut(section3_title), FadeOut(uc1), FadeOut(uc2))
        self.wait(0.5)

        # =========================================================================
        # Key Interview Insight & DPO Derivation
        # =========================================================================
        section4_title = Tex(r"Key Interview Insight: The Alignment Tax", color=RED).to_edge(UP)

        with self.voiceover(text="We now arrive at the most critical segment for your career progression. During senior machine learning system design interviews, you will rarely be asked just to define RLHF. You will be rigorously tested on its systemic flaws and trade-offs.") as tracker:
            self.play(Write(section4_title))
            self.wait(1.5)

        insight_box = Rectangle(width=10, height=3, color=RED, fill_color=RED_E, fill_opacity=0.1).shift(UP * 1.5)

        insight_text = Tex(
            r"1. \textbf{Capability Degradation:} Safer models often become worse at coding/math. \\",
            r"2. \textbf{Sycophancy:} Models simply flatter the user instead of seeking truth. \\",
            r"3. \textbf{Extreme Cost:} Maintaining the PPO RL loop is computationally massive.",
            color=BLACK
        ).scale(0.7).move_to(insight_box.get_center())

        with self.voiceover(text="Interviewers want you to discuss the concept of the 'Alignment Tax'. This refers to the frustrating phenomenon where heavily applying RLHF to make a model safer inevitably degrades its raw capabilities. An aligned model often becomes significantly worse at complex reasoning, mathematics, and intricate software engineering tasks compared to its base model equivalent.") as tracker:
            self.play(FadeIn(insight_box))
            self.play(Write(insight_text[0]))
            self.wait(2.5)

        with self.voiceover(text="Furthermore, RLHF often induces a failure mode known as sycophancy, or mode collapse. Because the reward model is trained on human preferences, and humans generally like being agreed with, the AI learns to simply flatter the user. It will confidently agree with a user's incorrect mathematical premise rather than assert the objective truth, just to maximize its perceived helpfulness score.") as tracker:
            self.play(Write(insight_text[1]))
            self.wait(2.5)

        with self.voiceover(text="Finally, from a pure engineering and infrastructure standpoint, maintaining a separate reward model while running Proximal Policy Optimization is computationally devastating. The memory overhead of keeping multiple enormous model weights in VRAM simultaneously is extremely expensive and notoriously unstable to scale.") as tracker:
            self.play(Write(insight_text[2]))
            self.wait(2.5)

        # Deep Dive: DPO Derivation via TransformMatchingTex
        with self.voiceover(text="Because of these severe engineering bottlenecks, the modern AI industry is rapidly pivoting. In an interview, explicitly bringing up DPO, or Direct Preference Optimization, will demonstrate that you are operating at the absolute cutting edge of AI engineering.") as tracker:
            self.wait(2)

        # Step 1: Standard RLHF Objective
        dpo_step1 = MathTex(
            r"\max_{\pi_\theta}", r"\mathbb{E}", r"_{(x, y)}", r"\left[", r"r_\phi(x, y)", r"-", r"\beta", r"\mathbb{KL}", r"(", r"\pi_\theta", r"||", r"\pi_{\text{ref}}", r")", r"\right]",
            color=BLACK
        ).scale(0.8).next_to(insight_box, DOWN, buff=0.8)

        with self.voiceover(text="Let's trace the mathematical derivation conceptually. Traditional RLHF attempts to maximize the expected reward generated by our learned reward model, denoted here as r phi, while strictly penalizing the model from drifting too far from its original reference weights using a KL divergence penalty. This requires loading both the policy and a separate reward model simultaneously.") as tracker:
            self.play(Write(dpo_step1))
            self.wait(3)

        # Step 2: DPO insight (reparameterization)
        dpo_step2 = MathTex(
            r"r^*(x, y)", r"=", r"\beta", r"\log", r"\frac{\pi_\theta(y|x)}{\pi_{\text{ref}}(y|x)}", r"+", r"Z(x)",
            color=BLACK
        ).scale(0.8).next_to(insight_box, DOWN, buff=0.8)

        with self.voiceover(text="The genius insight of Direct Preference Optimization is a mathematical reparameterization. DPO proves algebraically that the optimal reward function can be expressed entirely in terms of the language model's own probabilities. By mapping the reward directly to the log-ratio of the active policy versus the reference policy...") as tracker:
            self.play(TransformMatchingTex(dpo_step1, dpo_step2))
            self.wait(3)

        # Step 3: Final DPO Loss Function
        dpo_step3 = MathTex(
            r"\mathcal{L}_{\text{DPO}}", r"=", r"-", r"\mathbb{E}", r"_{(x, y_w, y_l)}", r"\left[", r"\log", r"\sigma", r"\left(", r"\beta", r"\log", r"\frac{\pi_\theta(y_w|x)}{\pi_{\text{ref}}(y_w|x)}", r"-", r"\beta", r"\log", r"\frac{\pi_\theta(y_l|x)}{\pi_{\text{ref}}(y_l|x)}", r"\right)", r"\right]",
            color=BLACK
        ).scale(0.7).next_to(insight_box, DOWN, buff=0.8)

        with self.voiceover(text="...we can completely eliminate the separate reward model and the unstable PPO algorithm. We arrive at the final DPO loss function, which directly optimizes the language model on the paired preference data using a simple binary cross-entropy objective. The model simply learns to increase the probability of the winning response, y w, and decrease the probability of the losing response, y l. This cuts memory requirements in half and vastly stabilizes training.") as tracker:
            self.play(TransformMatchingTex(dpo_step2, dpo_step3))
            self.wait(4)

        # Conclusion
        with self.voiceover(text="To summarize comprehensively: RLHF is incredibly powerful for initial human alignment, but comes with high alignment taxes, sycophancy risks, and massive infrastructural costs. Understanding how methodologies like Constitutional AI and Direct Preference Optimization solve these exact bottlenecks is the key to acing your senior AI system design interviews.") as tracker:
            self.play(Indicate(insight_box, color=RED))
            self.play(Indicate(dpo_step3, color=BLUE))
            self.wait(3.5)

        self.play(
            FadeOut(section4_title), FadeOut(insight_box),
            FadeOut(insight_text), FadeOut(dpo_step3)
        )
        self.wait(1)

        end_text = Tex(r"Keep Building,\\Keep Learning!", color=BLUE).scale(1.5)
        with self.voiceover(text="That concludes our deep architectural dive into Reinforcement Learning from Human Feedback. Take time to review these mathematical derivations. Keep building robust systems, keep learning, and best of luck with your AI engineering journey!") as tracker:
            self.play(Write(end_text))
            self.wait(3)

        self.play(FadeOut(end_text))
        self.wait(1)
