from manim import *
from manim_voiceover import VoiceoverScene
from manim_voiceover.services.gtts import GTTSService

class Day54TokenSampling(VoiceoverScene):
    def construct(self):
        self.camera.background_color = WHITE
        self.set_speech_service(GTTSService())

        # Overall title
        title = Text("Token Sampling: Temperature, Top-K, & Top-P", font_size=40, color=BLACK).to_edge(UP)
        with self.voiceover(text="Welcome to day 54 of AI Engineering Mastery. Today, we dive into one of the most critical aspects of large language models: Token Sampling, specifically covering Temperature, Top-K, and Top-P.") as tracker:
            self.play(Write(title))
            self.wait(1.5)

        # ---------------------------------------------------------------------
        # 1. WHAT IS IT?
        # ---------------------------------------------------------------------
        section1_title = Text("What is it?", font_size=32, color=BLUE).next_to(title, DOWN, buff=0.5)
        definition = Text(
            "Token sampling is the process of selecting the next word \nfrom a probability distribution generated by a language model.",
            font_size=24, color=BLACK
        ).next_to(section1_title, DOWN, buff=0.5)

        with self.voiceover(text="Let us begin with a fundamental definition. Token sampling is the process by which a language model chooses the very next word, or token, in a sequence, from a wide probability distribution of all possible vocabulary words.") as tracker:
            self.play(FadeIn(section1_title), Write(definition))
            self.wait(1.5)

        # Draw a bar chart showing probabilities
        labels = ["apple", "banana", "cat", "dog", "elephant"]
        probs = [0.55, 0.20, 0.15, 0.08, 0.02]

        bars = VGroup()
        for i, (label, prob) in enumerate(zip(labels, probs)):
            bar = Rectangle(height=prob * 5, width=0.8, color=BLACK, fill_color=BLUE, fill_opacity=0.7)
            text = Text(label, font_size=16, color=BLACK).next_to(bar, DOWN, buff=0.2)
            prob_text = Text(f"{prob:.2f}", font_size=16, color=BLACK).next_to(bar, UP, buff=0.2)
            group = VGroup(bar, text, prob_text)
            if i == 0:
                group.move_to(DOWN * 1.5 + LEFT * 3)
            else:
                group.next_to(bars[-1], RIGHT, buff=0.5).align_to(bars[-1][0], DOWN)
            bars.add(group)

        bars.center().shift(DOWN)

        with self.voiceover(text="Imagine the model is predicting the next word. It assigns a probability score to every word in its vocabulary. For instance, 'apple' might have a 55 percent chance, 'banana' 20 percent, and so on down a long tail. Without sampling, the model might just pick the highest probability every time.") as tracker:
            self.play(FadeIn(bars, shift=UP))
            self.wait(1.5)

        self.play(FadeOut(definition), FadeOut(bars), FadeOut(section1_title))

        # Temperature
        temp_title = Text("Temperature", font_size=32, color=RED).next_to(title, DOWN, buff=0.5)
        temp_def = Text("Scales the probabilities before they are applied.", font_size=24, color=BLACK).next_to(temp_title, DOWN)

        # Math formulation for softmax with temperature - derived step by step
        math_softmax = MathTex(
            r"p_i = \frac{\exp(z_i)}{\sum_j \exp(z_j)}",
            color=BLACK
        ).next_to(temp_def, DOWN, buff=0.5)

        math_temp = MathTex(
            r"p_i = \frac{\exp(z_i / T)}{\sum_j \exp(z_j / T)}",
            color=BLACK
        ).next_to(temp_def, DOWN, buff=0.5)

        with self.voiceover(text="The first concept is Temperature. Temperature scales the output logits of the model before they are passed through the standard softmax function to become probabilities.") as tracker:
            self.play(FadeIn(temp_title), Write(temp_def))
            self.play(Write(math_softmax))
            self.wait(1.5)

        with self.voiceover(text="By introducing a Temperature parameter T, we divide the logits by T before the exponentiation. Notice how T is applied to both the numerator and denominator.") as tracker:
            self.play(TransformMatchingTex(math_softmax, math_temp))
            self.wait(1.5)

        with self.voiceover(text="A low temperature, less than one, makes the distribution sharper. High probability tokens become even more likely, and low probability tokens become practically zero. A high temperature, greater than one, flattens the distribution, making all words more equally likely, which increases randomness and creativity.") as tracker:
            self.play(Indicate(math_temp, color=RED, scale_factor=1.1))
            self.wait(1.5)

        self.play(FadeOut(temp_title), FadeOut(temp_def), FadeOut(math_temp))

        # Top-K
        topk_title = Text("Top-K Sampling", font_size=32, color=GREEN).next_to(title, DOWN, buff=0.5)
        topk_def = Text("Sort probabilities and keep only the top K tokens.", font_size=24, color=BLACK).next_to(topk_title, DOWN)

        with self.voiceover(text="Next is Top-K sampling. In Top-K, we sort the entire vocabulary by probability, and we strictly keep only the top K tokens, discarding all the rest.") as tracker:
            self.play(FadeIn(topk_title), Write(topk_def))
            self.wait(1.5)

        with self.voiceover(text="If K is 3, we only ever sample from the 3 most likely next words, no matter how confident or unsure the model is. The remaining probabilities are redistributed among these three.") as tracker:
            # Show a list shrinking
            list_text = Text("Top K=3: [ apple(0.55), banana(0.20), cat(0.15) ]", font_size=24, color=BLACK).next_to(topk_def, DOWN, buff=0.5)
            self.play(FadeIn(list_text))
            self.wait(1.5)

        self.play(FadeOut(topk_title), FadeOut(topk_def), FadeOut(list_text))

        # Top-P
        topp_title = Text("Top-P (Nucleus) Sampling", font_size=32, color=PURPLE).next_to(title, DOWN, buff=0.5)
        topp_def = Text("Sort and keep tokens until their cumulative probability reaches P.", font_size=24, color=BLACK).next_to(topp_title, DOWN)

        with self.voiceover(text="Finally, there is Top-P, also known as Nucleus Sampling. Instead of keeping a fixed number of tokens, we sort them and keep adding tokens to our candidate pool until the cumulative probability reaches a specific threshold P, such as 0.9.") as tracker:
            self.play(FadeIn(topp_title), Write(topp_def))
            self.wait(1.5)

        with self.voiceover(text="This is dynamic. If the model is very confident, the Top-P pool might only contain one or two words. If the model is unsure, the pool expands to include dozens of words to reach the threshold P.") as tracker:
            list_text2 = Text("If P=0.90: [ apple(0.55) + banana(0.20) + cat(0.15) = 0.90 ] -> keep 3", font_size=24, color=BLACK).next_to(topp_def, DOWN, buff=0.5)
            self.play(FadeIn(list_text2))
            self.wait(1.5)

        self.play(FadeOut(topp_title), FadeOut(topp_def), FadeOut(list_text2))

        # ---------------------------------------------------------------------
        # 2. WHY DO WE NEED IT?
        # ---------------------------------------------------------------------
        section2_title = Text("Why do we need it?", font_size=32, color=BLUE).next_to(title, DOWN, buff=0.5)

        with self.voiceover(text="Now, why do we need sampling techniques at all? Why not just always pick the most likely word?") as tracker:
            self.play(FadeIn(section2_title))
            self.wait(1.5)

        greedy_title = Text("Without Sampling (Greedy Decoding)", font_size=28, color=RED).next_to(section2_title, DOWN, buff=0.5)
        greedy_text = Text('"I went to the store and bought a dog and a dog and a dog..."', font_size=24, color=BLACK).next_to(greedy_title, DOWN, buff=0.3)

        with self.voiceover(text="Without sampling, we use greedy decoding, always picking the top token. This often results in text that is incredibly boring, highly repetitive, and gets stuck in infinite loops, like 'I went to the store and bought a dog and a dog and a dog'.") as tracker:
            self.play(Write(greedy_title), Write(greedy_text))
            self.wait(1.5)

        sampling_title = Text("With Sampling", font_size=28, color=GREEN).next_to(greedy_text, DOWN, buff=0.5)
        sampling_text = Text('"I went to the store and bought a delicious organic apple."', font_size=24, color=BLACK).next_to(sampling_title, DOWN, buff=0.3)

        with self.voiceover(text="By introducing randomness through Temperature, Top-K, and Top-P, the model can choose diverse, contextually appropriate, and creative paths, generating natural-sounding human language.") as tracker:
            self.play(Write(sampling_title), Write(sampling_text))
            self.wait(1.5)

        self.play(FadeOut(section2_title), FadeOut(greedy_title), FadeOut(greedy_text), FadeOut(sampling_title), FadeOut(sampling_text))


        # ---------------------------------------------------------------------
        # 3. USE CASES
        # ---------------------------------------------------------------------
        section3_title = Text("Real-World Use Cases", font_size=32, color=BLUE).next_to(title, DOWN, buff=0.5)

        with self.voiceover(text="Let us explore two distinct real-world use cases where these sampling parameters are tuned entirely differently.") as tracker:
            self.play(FadeIn(section3_title))
            self.wait(1.5)

        # Use Case 1
        uc1_box = RoundedRectangle(height=2.5, width=12, corner_radius=0.2, color=GREEN, fill_color=WHITE, fill_opacity=1).next_to(section3_title, DOWN, buff=0.5)
        uc1_text1 = Text("1. ChatGPT / Claude (Creative Chat)", font_size=28, color=BLACK).next_to(uc1_box.get_top(), DOWN, buff=0.2)
        uc1_text2 = Text("High Temperature (~0.7) and high Top-P (~0.95)", font_size=24, color=BLACK).next_to(uc1_text1, DOWN, buff=0.3)
        uc1_text3 = Text("Result: Engaging, diverse, and unpredictable conversations.", font_size=22, color=BLACK).next_to(uc1_text2, DOWN, buff=0.2)
        uc1_group = VGroup(uc1_box, uc1_text1, uc1_text2, uc1_text3)

        with self.voiceover(text="First, general purpose conversational assistants like ChatGPT or Anthropic's Claude. When generating creative stories or brainstorming, they use a higher temperature, around 0.7, and a high Top-P value. This allows the model to select from a wider pool of words, resulting in engaging, diverse, and unpredictable conversational flow.") as tracker:
            self.play(FadeIn(uc1_box), Write(uc1_text1))
            self.play(Write(uc1_text2), Write(uc1_text3))
            self.wait(1.5)

        # Use Case 2
        uc2_box = RoundedRectangle(height=2.5, width=12, corner_radius=0.2, color=BLUE, fill_color=WHITE, fill_opacity=1).next_to(uc1_box, DOWN, buff=0.5)
        uc2_text1 = Text("2. GitHub Copilot (Code Generation)", font_size=28, color=BLACK).next_to(uc2_box.get_top(), DOWN, buff=0.2)
        uc2_text2 = Text("Low Temperature (~0.1 to 0.2)", font_size=24, color=BLACK).next_to(uc2_text1, DOWN, buff=0.3)
        uc2_text3 = Text("Result: Highly deterministic, syntactically exact code.", font_size=22, color=BLACK).next_to(uc2_text2, DOWN, buff=0.2)
        uc2_group = VGroup(uc2_box, uc2_text1, uc2_text2, uc2_text3)

        with self.voiceover(text="On the other hand, consider GitHub Copilot generating software code. Code requires precise syntax and exact logic. Here, you want a very low temperature, around 0.1, making the model highly deterministic and nearly greedy, ensuring it outputs the single most technically accurate piece of code without random hallucinations.") as tracker:
            self.play(FadeIn(uc2_box), Write(uc2_text1))
            self.play(Write(uc2_text2), Write(uc2_text3))
            self.wait(1.5)

        self.play(FadeOut(section3_title), FadeOut(uc1_group), FadeOut(uc2_group))


        # ---------------------------------------------------------------------
        # 4. KEY INTERVIEW INSIGHT
        # ---------------------------------------------------------------------
        insight_title = Text("Key Interview Insight", font_size=32, color=RED).next_to(title, DOWN, buff=0.5)

        insight_box = Rectangle(height=4.5, width=12, color=RED, fill_color=WHITE, fill_opacity=1).next_to(insight_title, DOWN, buff=0.5)
        insight_text1 = Text("Tradeoff: Static vs. Dynamic Confidence", font_size=28, color=BLACK, weight=BOLD).next_to(insight_box.get_top(), DOWN, buff=0.4)
        insight_text2 = Text("• Top-K is fixed: Always keeps exactly K tokens. If K=50, it keeps 50.", font_size=24, color=BLACK).next_to(insight_text1, DOWN, buff=0.4).align_to(insight_box.get_left(), RIGHT).shift(RIGHT*1)
        insight_text3 = Text("• Top-P is dynamic: Adapts to the model's confidence.", font_size=24, color=BLACK).next_to(insight_text2, DOWN, buff=0.4).align_to(insight_text2, LEFT)
        insight_text4 = Text("Interviewers want to see you know that Top-P handles 'flat' vs 'peaked'\ndistributions better than a hardcoded Top-K.", font_size=24, color=RED).next_to(insight_text3, DOWN, buff=0.6).align_to(insight_box, DOWN).shift(UP*0.5)

        insight_group = VGroup(insight_box, insight_text1, insight_text2, insight_text3, insight_text4)

        with self.voiceover(text="Finally, let us discuss the key interview insight you must remember. Interviewers love to test if you understand the tradeoff between static and dynamic confidence when comparing Top-K and Top-P.") as tracker:
            self.play(FadeIn(insight_title), FadeIn(insight_box))
            self.play(Write(insight_text1))
            self.wait(1.5)

        with self.voiceover(text="The core issue is that Top-K is completely fixed. If you set K to 50, the model always considers exactly 50 tokens. If the model is extremely confident about just two words, it is still forced to consider 48 highly unlikely, terrible words, which can introduce garbage text.") as tracker:
            self.play(Write(insight_text2))
            self.wait(1.5)

        with self.voiceover(text="Top-P, however, is dynamic. It adapts to the shape of the probability distribution. If the distribution is sharply peaked, Top-P naturally restricts the pool to just a few highly confident words. If the distribution is flat, it expands the pool.") as tracker:
            self.play(Write(insight_text3))
            self.wait(1.5)

        with self.voiceover(text="Therefore, knowing that Top-P dynamically handles flat versus peaked distributions much better than a hardcoded Top-K parameter is exactly what senior AI engineers and interviewers are looking for in your technical system design interviews.") as tracker:
            self.play(Write(insight_text4))
            self.wait(1.5)

        self.play(FadeOut(insight_title), FadeOut(insight_group), FadeOut(title))

        # Outro
        outro = Text("Happy Coding!", font_size=48, color=BLUE)
        with self.voiceover(text="Thank you for watching this deep dive into token sampling. Master these parameters, and you will have immense control over the output of large language models. Happy coding!") as tracker:
            self.play(Write(outro))
            self.wait(2)

        self.play(FadeOut(outro))
